eileenmcnaughton/nz.co.fuzion.civixero

CRM/Civixero/BankTransaction.php, CRM/Civixero/Contact.php, CRM/Civixero/Invoice.php
As discussed in issue #11 
To understand the changes, $accountInvoice and $result are FALSE when the hook returns $save as FALSE.
- For Contacts I elected to change the push() function.
- For Invoices I changed the functions called by push() [essentially so savePushResponse() got called to update the account_invoice]. 
- I don't push Bank Transactions so I made the change analogous to the one for Invoices. You should be wary of that change as it's not tested.
=> Avoid talking to Xero if PushAlterMapped() sets  $save to FALSE

CRM/Civixero/Invoice.php
This is an alternative implementation to solve issue #14 
The advantage of this approach is that the 'accounts_needs_update' flag is set back to '0'
=> Prevent Invoices that were DELETED or VOIDED in Xero from being pushed back

CRM/Civixero/Contact.php
The recent database change to default accounts_needs_update to 1 means it needs to be set to 0 in cases where we don't want to update the accounts system.
When pulling contacts from Xero to CiviCRM, we don't need to update Xero again.
BTW, pulling invoices already sets accounts_needs_update to 0, so it's OK.
=> Set accounts_needs_update to 0 when pulling contacts

CRM/Civixero/Invoice.php
Improvements ...
1. Improve the Bank Transaction test
2. capture the Invoice Id if not yet set
Explanation ...
1. Looking at the if statement, the assignments all assume $result['BankTransactions'] is set. So it makes sense to test for this. Also $result is clearly not an Invoice if that is true.
2. The response to the push includes the Invoice Id so why not capture it? Saves us waiting for a pull. The change also protects against the unlikely (impossible?) case that the Invoice Id changes.
=> 2 improvements when handling Xero's response after pushing an Invoice

CRM/Civixero/Contact.php
Update existing AccountContact entity if one matches the ContactID returned from Xero.
This fixes a DB contrstraint violation that crops up when a contact has previously been pulled into the civicrm_account_contact table and a later push results in a reference to the same contact ID in Xero.
=> Update existing AccountContact entity if one matches.

CRM/Civixero/Contact.php
Introduced a bug in #33 -- Should've checked that one more carefully.
One of our systems stopped pushing contacts altogether as too many of them were suddenly failing because they matched themselves.  This fixes that.
Sorry! 😳
=> SUP-2549: Don't find matching contacts for the same contact id.

CRM/Civixero/Page/AJAX.php, CRM/Civixero/Page/XeroErrorLogs.php, Civixero.civix.php, Civixero.php, css/civixero_styles.css, js/civixero_errors.js, templates/CRM/Civixero/Page/XeroErrorLogs.tpl, xml/Menu/Civixero.xml
Providing an administrative alert within CiviCRM when there are errors during the Xero sync process. Currently, there is no way to alert that a sync process has failed.
The alert will appear in the CiviCRM status page and as a pop-up administrative alert when logging into CiviCRM.
Admin would be able to see these error messages on three places.
1. CiviCRM System Status page
2. Individual Xero sync error logs page under (Administer > Xero > Xero Error Logs >  )
3. Contact view page
**Click Here** link will redirect user to Individual Xero sync error logs page.
From this page User would be able to **Clear** the error or allow the record to **Resync** by clicking on **Retry** link.
Clicking on contact name will redirect user to contact view page.
Clicking on (?) icon next to the error will …
=> CIVIXERO-7-11: Administrative alert within CiviCRM when there are errors during the Xero sync process

CRM/Civixero/Contact.php
(Agileware ref. CIVIXERO-21)
Otherwise it stumbles over `NULL != $record['contact_id']`.
Also fixes a fatal ArgumentCountError when throwing an exception
where a contact_id is found, but refers to a different Contact.
=> Fix contact push case where AccountContact record has NULL contact_id

CRM/Civixero/Page/XeroErrorLogs.php, templates/CRM/Civixero/Page/XeroErrorLogs.tpl
Overview
------
The url in the error log page is wrong. For example, in WordPress, the retry url is `https://website.com/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fajax%2Fcivixero%2Fsync%2Finvoice%2Ferrors%2Fretry?id={id}`.
This can be fixed by using `CRM_Utils_System::url`.
Before
------
Wrong url with two question marks in WordPress.
After
------
Correct url.
Comment
------
Agileware ref: CIVIXERO-30
=> Fix url for WordPress

CRM/Civixero/Page/XeroErrorLogs.php
Overview
------
Missing part for #57 
Before
------
No URL on contact error log page.
After
------
Correct URL on contact error log page.
Comment
------
Agileware ref: CIVIXERO-30
=> Fix url for contacts error log page

CRM/Civixero/Page/AJAX.php
Overview
------
Clearing the error on invoice error log page does not mark the error to be skipped by the push job. So the error shows up again after the scheduled job executed.
Before
------
The error pops up again.
After
------
The error does not pop up again.
Comment
------
Agileware ref: CIVIXERO-32
=> Skip cleared invoice error when pushing

CRM/Civixero/Page/Inline/ContactSyncErrors.php, CRM/Civixero/Page/Inline/ContactSyncLink.php, CRM/Civixero/Page/Inline/ContactSyncStatus.php, CRM/Civixero/Page/Inline/InvoiceSyncErrors.php, CRM/Civixero/Page/Inline/InvoiceSyncLink.php, Civixero.php, templates/CRM/Civixero/ContactSyncBlock.tpl, templates/CRM/Civixero/Page/Inline/ContactSyncErrors.tpl, templates/CRM/Civixero/Page/Inline/ContactSyncLink.tpl, templates/CRM/Civixero/Page/Inline/ContactSyncStatus.tpl, templates/CRM/Civixero/Page/Inline/InvoiceSyncErrors.tpl, templates/CRM/Civixero/Page/Inline/InvoiceSyncLink.tpl
This PR implements the new CiviCRM Blocks for CiviXero. Implements Contact sync status, Invoice sync errors, Contact sync errors, Contact Sync link, Invoice sync link blocks.
CiviCRM Blocks are then available in the CiviCRM Contact Summary Layout Editor, https://github.com/civicrm/org.civicrm.contactlayout
This PR removes the page_run_hook function which previously added links on the Contact Summary screen for the Xero Contact because this has been replaced by the CiviCRM Blocks method of adding the links.
_Agileware Ref: CIVIXERO-18_
=> Added contact/invoice blocks as region blocks and defined them in contactSummaryBlocks hook.

CRM/Civixero/Page/Inline/ContactSyncErrors.php, CRM/Civixero/Page/Inline/InvoiceSyncErrors.php, templates/CRM/Civixero/Page/Inline/ContactSyncErrors.tpl, templates/CRM/Civixero/Page/Inline/InvoiceSyncErrors.tpl
Looks like the original code did a bit too much copy/paste and introduced errors in the IDs for the links
=> Further fix for IDs on sync blocks

CRM/Civixero/Invoice.php
Recent change to **something** in CiviCRM meant that we now see stuff with no tax account come in with the string '0.00' instead of an actual float value.
This updates the logic for setting the line item types to take that into account.
Main application for this is where organisations have Tax & Invoicing enabled, and have tax configured in Xero (e.g. GST), but have no tax accounts or calculation in CiviCRM.
Before
------
When the tax amounts are all zero, Invoices would be pushed to Xero accounts with tax applied as tax exclusive when they should be tax inclusive, causing Xero to add extra tax on top.
After
-----
Under the same circumstances, Invoices are pushed as tax inclusive, and do not get extra tax added by Xero.
=> CIVIXERO-40: Fix tax_amount test to account for string '0.00'

CRM/Civixero/Contact.php, api/v3/Civixero/Contactpull.php
This allows you to "pull" a specific Xero contact record into CiviCRM using the API.
=> Add parameter to Civixero.contactpull to pull a single contact

CRM/Civixero/Invoice.php, settings/Civixero.setting.php
For some reason we were passing the default currency of CiviCRM instead of the actual currency of the contribution.
Also clarify the invoice sync statuses in settings (so they are in sequential order and labelled as per Xero).
=> Push invoices from CiviCRM to Xero using actual currency instead of CiviCRM default

CRM/Civixero/OAuth2/Xero.php
`[info] $CiviXeroDebug = Storing renewed token.` is added to the logs multiple times a day. It is not helpful because it fills the logs and does not tell us anything. This PR removes it and adds another one in the case that a new token is NOT obtained - which would be more useful if troubleshooting!
`$connectionsURL` is unused.
=> Remove unhelpful log message and replace with one that could be useful

CRM/Civixero/Contact.php, settings/Civixero.setting.php
This currently only works with email.
It allows you to specify a location type instead of always using the Primary email address. So for example you can set Xero to sync the "Billing" email address so that the accounts department receives the invoices. But you set the primary email to their technical contact so the accounts department does not get scared when they hear about security update notifications...
=> Support syncing a specific location type for email instead of always using primary

CRM/Civixero/Contact.php, api/v3/Civixero/Contactpush.php
Hopefully will be able to follow this up with a link in the UI to "push now" when it says "Contact is queued for sync with Xero". But this is useful by itself for debugging etc. because you can use the API directly to push a single contact.
Also fixed an issue with reporting an error response from Xero when pushing a contact
=> Allow you to push a single contact by CiviCRM contact ID using the API

CRM/Civixero/Page/Inline/ContactSyncStatus.php, templates/CRM/Civixero/Page/Inline/ContactSyncStatus.tpl
Extracted from #101
If an error occurs the contact summary would just display "queue sync to xero" instead of indicating that an error occurred. Now it indicates that an error occurred and endlessly clicking "queue sync to xero" isn't going to help..
=> Fix display of sync status errors on contact summary

CRM/Civixero/Base.php, CRM/Civixero/Contact.php, CRM/Civixero/Exception/XeroThrottle.php, CRM/Civixero/Invoice.php, settings/Civixero.setting.php
If something is going wrong  or you're trying to do an initial big sync-up CiviXero will repeatedly try to do that wrong thing. That'll quickly cause you to hit API limits with Xero and we should be respecting that limit (ie. XeroThrottleException) and not just blindly retrying when Xero is telling us not to.
This implements a simple set/reset for the Xero throttle that will prevent sync jobs running for 1 hour if the rate has been exceeded.
=> If Xero API throttles us wait for one hour before retrying

settings/Civixero.setting.php
@eileenmcnaughton Looks like you may have changed this to multiple when updating settings metadata. It shouldn't be
=> Fix location type setting

CRM/Civixero/Form/XeroAuthorize.php, Civixero.php, templates/CRM/Civixero/Form/XeroAuthorize.tpl
Sometimes you need to re-authorize and you start getting errors in job logs 'invalid_grant'. Make it a bit more friendly/clearer by providing system check and showing expiry date.
Quickbooks has a fixed expiry time for the refresh token. Xero gets a new refresh token (valid for 60 days) every time it gets a new access token (valid for 30 minutes). So in theory it should never expire / need re-authorization. But that's not actually true and sometimes it just starts announcing "invalid_grant" in the sync logs which actually means the you need to re-authorize with Xero.
This PR is probably not a perfect solution but it makes it a bit more user-visible as to what needs to be done to make it work and also to troubleshoot / debug.
=> Access token expiry

CRM/Civixero/Page/Inline/ContactSyncStatus.php, templates/CRM/Civixero/Page/Inline/ContactSyncStatus.tpl
This modifies logic that I put in place recently. It's actually ok for there not to be an AccountContact record but there should be a way to create one. This makes it possible again.
=> If no AccountContact record show 'Queue sync to Xero' link

CRM/Civixero/Base.php, CRM/Civixero/Form/XeroAuthorize.php, CRM/Civixero/Invoice.php, CRM/Civixero/Settings.php
Multiple functions to retrieve settings that work slightly differently. One of the causes of occasional bugs with transient invalid access tokens - that fail and then work next time you run.
=> Remove duplicate functions to get/set settings

CRM/Civixero/Contact.php
Contact push job fails with:
```
TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in
.../web/sites/default/civicrm/ext/nz.co.fuzion.civixero/CRM/Civixero/Contact.php on line 160 #0 
.../web/sites/default/civicrm/ext/nz.co.fuzion.civixero/api/v3/Civixero/Contactpush.php(50): CRM_Civixero_Contact->push()
```
I think checking for null is a fine change? @eileenmcnaughton
=> Fix fatal error on contact push sched job

CRM/Civixero/BankTransaction.php, packages/Xero/Xero.php
Regression due to https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/commit/4d580a01f36fee1fe33c72e8b971f94b106a642d?
>Got error 'PHP message: PHP Fatal error:  Declaration of CRM_Civixero_BankTransaction::getNotUpdateCandidateResponses() must be compatible with CRM_Civixero_Invoice::getNotUpdateCandidateResponses(): array in /sites/default/civicrm/extensions/nz.co.fuzion.civixero/CRM/Civixero/BankTransaction.php on line 138PHP message: PHP Stack trace:PHP message: PHP   
Stopped cron from running and no invoice being pushed to xero.
PR also removes an undefined variable `$nvpreq` from packages/Xero/Xero.php.
=> Fix fatal error on invoice push job

CRM/Civixero/Contact.php, CRM/Civixero/Invoice.php
One of the other fields will be modified if we need to update and this reduces the amount of updates we do (which reduces the amount of logging if extended logging enabled)
=> Don't trigger update on accounts_data change.

CRM/Civixero/Invoice.php
Contribution invoices with accounts_status_id = NULL isn't processed by the scheduled job. This was fixed in https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/pull/132 but the PR was closed as most of the fixed were already included in MJW branch. The problem with accounts_status_id is still there.
=> Fix invoice job to process accounts_status_id = NULL contributions

CRM/Civixero/Contact.php, CRM/Civixero/Invoice.php
Clarify some variables. I was looking into https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/issues/165 and getting confused.
=> Rename Xero 'ID' vars for clarity. If invoice UUID is passed in add it to the invoice

packages/Xero/Xero.php
If `curl_exec()` fails it returns FALSE or something falsey which causes line 351 `throw new XeroException($xero_response);` to emit a PHP warning about undefined variable.
=> Throw exception on curl error instead of undefined variable xero_response

CRM/Civixero/Invoice.php
The code derives the contribution ID from the Xero Invoice ID but then crashes when saving because the contribution ID doesn't exist and it triggers a foreign key constraint on contribution.
=> If we have deleted a contribution in CiviCRM don't trigger DB constraint error when saving AccountInvoice

CRM/Civixero/Contact.php, CRM/Civixero/Invoice.php, Civi/Api4/Action/Xero/ContactPull.php, Civi/Api4/Action/Xero/InvoicePull.php, api/v3/Civixero/Contactpull.php, api/v3/Civixero/Invoicepull.php
This switches over Contact and Invoice Pull to use the newer Xero API from the SDK library. The new library also gives us quite a bit of flexibility in terms of params that could be passed but I've not really used those yet and am just parsing existing params in so it stays compatible.
Added API4 for ContactPull and InvoicePull - they don't currently perform the sync though and we might want to consider renaming them or making them do the sync as well. It's useful for debug to be able to pull data from Xero without syncing so useful to have those APIs. But we should eventually replace the API3 calls that currently do the sync.
It also fixes a nasty bug that at some point the scheduled jobs stopped respecting the "start_date" for sync and have started pulling *all* contacts/invoices …
=> Use newer Xero API from SDK library for Contact Pull and Invoice Pull

managed/job.mgd.php
Makes sense for these jobs to default to update=unmodified
and some currently have update in the wrong place.
The main thing is that they don't enable/disable themselves but we've specified is_active so that shouldn't happen.
=> Set managed entities to update=unmodified
