packages/Xero/Xero.php
Only execute the OAuth class declarations if OAuthException has not already been declared. OAuth classes may be used by other services.
=> OAuth classes may already be declared

CRM/Civixero/Invoice.php
Please see the discussion at issue #8
=> Stop 'accounts_modified_date is not a valid date: 0000-00-00 00:00:00'

CRM/Civixero/Job/job.mgd.php, Civixero.php
Supporting hook implementation for eileenmcnaughton/nz.co.fuzion.accountsync#21
=> Implement Plugin mechanism

CRM/Civixero/Invoice.php, settings/Civixero.setting.php
Adds an option to provide a prefix to the created invoice number in Xero.
=> Invoice number prefix

packages/Xero/Xero.php
I found some html entities sneaking in from user supplied data to be recoded before sending through.
=> Xero package - decode from HTML entities before encoding to XML.

CRM/Civixero/Upgrader.php, CRM/Civixero/Upgrader/Base.php, Civixero.civix.php
`civix generate:upgrader` Changes.
=> Add civix update for upgrader

CRM/Civixero/Page/Inline/ContactSyncErrors.php, CRM/Civixero/Page/Inline/InvoiceSyncErrors.php
=> Fix "Xero Contact" link to use the right ID

templates/CRM/Civixero/Page/Inline/ContactSyncLink.tpl
Update to use the "newer" style link in Xero
=> Update contact link

README.md
Improve ambiguous OAuth 2.0 redirect URI instructions
=> Improve ambiguous OAuth 2.0 redirect URI instructions

README.md
Create section for Linking from Xero to CiviCRM
=> Create section for Linking from Xero to CiviCRM

CRM/Civixero/Job/Job.mgd.php
Xero Authorize form shows the state of these jobs and advises you to enable them when ready.
=> Ship with scheduled jobs disabled so we don't accidently sync anything without first configuring

CRM/Civixero/Base.php, CRM/Civixero/OAuth2/TokenStoreDefault.php, CRM/Civixero/Upgrader.php, Civi/Xero/ConnectorInterface.php, settings/Civixero.setting.php
@eileenmcnaughton  Seems like the conversion only got half done in the code? This finishes it.
=> Finish conversion to separate oauth settings

CRM/Civixero/Base.php, CRM/Civixero/Form/XeroAuthorize.php, CRM/Civixero/OAuth2/TokenStoreDefault.php, CRM/Civixero/OAuth2/TokenStoreInterface.php, CRM/Civixero/OAuth2/Xero.php
Ok, this fixes the access token issues in the latest version
=> Fix handling of token renewal

CRM/Civixero/Invoice.php
This was wrong - https://developer.xero.com/documentation/api/accounting/invoices#invoice-status-codes
=> Fix invoice status

CRM/Civixero/Contact.php, info.xml
This is the same function & signature used in Matt's re-write and adds the extra contact is not null
=> Extract getContactsRequiringPushUpdate

CRM/Civixero/Base.php, CRM/Civixero/Contact.php, CRM/Civixero/Invoice.php, Civixero.php, tests/phpunit/ContactPushTest.php
Note I diverged on the handling of the throttle, moving it to a listener although am still testing the approach
=> Improve alignment with Matt's branch

CRM/Civixero/Contact.php, docs/releasenotes.md, info.xml
This is pretty much unchanged from what Matt was doing - just the output of the function is unchanged from before cos it feels kinda messy & I'm not sure what we should settle on
=> Bring across Matts work on Contact pull

Civixero.php, templates/CRM/Civixero/Page/Inline/ContributionInvoiceLink.tpl
=> Add invoice status to contribution view!

CRM/Civixero/Invoice.php
@eileenmcnaughton set of small fixes for invoices following 3.0 release and testing.
* Add more error recording.
* Don't try to change existing contribution_id on pull.
* only try to create contribution if we succeeded with AccountsInvoice update.
=> Invoice pull fixes.

CRM/Civixero/Contact.php
Otherwise they'll just keep on failing...
=> Don't push Contacts with errors

CRM/Civixero/Contact.php
If we don't have an Address/Phone don't send it to Xero as a blank entry as this can overwrite data at Xero.
=> Don't push Address/Phone to Xero if empty
